apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  # {{- template "mychart.labels" . }}
  labels:
{{ include "mychart.app" . | indent 4}}
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  # drink: {{ .drink | default "tea" | quote}}
  # food: {{ .food | upper | quote}}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  release: {{ $relname }}
  {{- end }}
  {{- if eq .Values.favorite.drink "peisi"}}
  mug: "aaaa"
  {{- end}}
  toppings: |-
    {{- range $index, $topping :=  .Values.pizzaToppings }}
      {{ $index }}: {{ $topping}}
    {{- end }} 
  sizes: |-
    {{- range tuple "small" "medium" "large" }}
    - {{ . | title | quote}}
    {{- end }}
{{ include "mychart.app" . | indent 2}} 
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}